-- CreateEnum
CREATE TYPE "OrderType" AS ENUM ('SINGLE', 'SUBSCRIPTION', 'INITIAL_SUBSCRIPTION', 'UPGRADE', 'DOWNGRADE', 'CHANGE_PLAN', 'CHANGE_ADDON', 'CHANGE_PRODUCT', 'CHANGE_QUANTITY');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "type" "OrderType" NOT NULL DEFAULT 'SINGLE';
